
                                      <div class="region region-content">
                                        <div class="block block-system" id="block-system-main">
                                          <div class="content">
                                            <div class="node node-group-content- node-promoted node-teaser contextual-links-region clearfix" id="node-3">

                                              <h2>
                                                <a href="/acquia_drupal/content/first-group-0">First group</a>
                                              </h2>
                                              <div class="contextual-links-wrapper contextual-links-processed"><a href="#" class="contextual-links-trigger">Configure</a><ul class="contextual-links"><li class="node-edit first"><a href="/acquia_drupal/node/3/edit?destination=node">Edit</a></li>
                                                  <li class="node-delete last"><a href="/acquia_drupal/node/3/delete?destination=node">Delete</a></li>
                                                </ul></div>
                                              <div class="meta submitted">
                                                Submitted by <a class="username" title="View user profile." href="/acquia_drupal/users/admin">admin</a> on Mon, 05/06/2013 - 16:14    </div>

                                              <div class="content clearfix">
                                              </div>

                                              <div class="link-wrapper">
                                                <ul class="links inline"><li class="node-readmore first last"><a title="First group" rel="tag" href="/acquia_drupal/content/first-group-0">Read more<span class="element-invisible"> about First group</span></a></li>
                                                </ul>    </div>


                                            </div>
                                      
                                          </div>
                                        </div>
                                      </div>