
        <h2 class="element-invisible">Main menu</h2>
        <ul class="links clearfix" id="main-menu-links">
          <li class="menu-home first last active"><a class="active" href="/acquia_drupal/">Home</a></li>
          <li class="menu-register first last"><a class="active" href="/acquia_drupal/">Register</a></li>
          <li class="menu-logout first last"><a class="active" href="/acquia_drupal/">Logout</a></li>
</ul>

