<div class="section">
  <div class="region region-sidebar-second">
    <div class="block block-node contextual-links-region" id="block-node-recent">
      <h2>Recent content</h2>
      <div class="contextual-links-wrapper contextual-links-processed"><a href="#" class="contextual-links-trigger">Configure</a><ul class="contextual-links"><li class="block-configure first last"><a href="/acquia_drupal/admin/structure/block/manage/node/recent/configure?destination=node">Configure block</a></li>
        </ul></div>
      <div class="content">
        <table>
          <tbody>
            <tr class="odd"><td class="title-author"><div class="node-title"><a href="/acquia_drupal/content/first-group-0">First group</a></div><div class="node-author"><a class="username" title="View user profile." href="/acquia_drupal/users/admin">admin</a></div></td><td class="edit"><a href="/acquia_drupal/node/3/edit?destination=node">edit</a></td><td class="delete"><a href="/acquia_drupal/node/3/delete?destination=node">delete</a></td> </tr>
            <tr class="even"><td class="title-author"><div class="node-title"><a href="/acquia_drupal/content/first-group">First group</a></div><div class="node-author"><a class="username" title="View user profile." href="/acquia_drupal/users/admin">admin</a></div></td><td class="edit"><a href="/acquia_drupal/node/2/edit?destination=node">edit</a></td><td class="delete"><a href="/acquia_drupal/node/2/delete?destination=node">delete</a></td> </tr>
            <tr class="odd"><td class="title-author"><div class="node-title"><a href="/acquia_drupal/content/welcome-your-new-acquia-drupal-website">Welcome to your new Acquia Drupal website!</a></div><div class="node-author"><a class="username" title="View user profile." href="/acquia_drupal/users/admin">admin</a></div></td><td class="edit"><a href="/acquia_drupal/node/1/edit?destination=node">edit</a></td><td class="delete"><a href="/acquia_drupal/node/1/delete?destination=node">delete</a></td> </tr>
          </tbody>
        </table>
        <div class="more-link"><a title="Show more content" href="/acquia_drupal/admin/content">More</a></div>  </div>
    </div>
  </div>
</div>


