<div class="section">
  <div class="region region-sidebar-first">
    <div class="block block-search contextual-links-region" id="block-search-form">
      <div class="contextual-links-wrapper contextual-links-processed"><a href="#" class="contextual-links-trigger">Configure</a><ul class="contextual-links"><li class="block-configure first last"><a href="/acquia_drupal/admin/structure/block/manage/search/form/configure?destination=node">Configure block</a></li>
        </ul>
      </div>
      <div class="content">
        <form accept-charset="UTF-8" id="search-block-form" method="post" action="/acquia_drupal/"><div><div class="container-inline">
              <h2 class="element-invisible">Search form</h2>
              <div class="form-item form-type-textfield form-item-search-block-form">
                <label for="edit-search-block-form--2" class="element-invisible">Search </label>
                <input type="text" class="form-text" maxlength="128" size="15" value="" name="search_block_form" id="edit-search-block-form--2" title="Enter the terms you wish to search for.">
              </div>
              <div id="edit-actions" class="form-actions form-wrapper"><input type="submit" class="form-submit" value="Search" name="op" id="edit-submit"></div><input type="hidden" value="form-4--jxcwY2CVZ08sXNcv6AzErz-ElWlOdXAxGa5BzKuo" name="form_build_id">
              <input type="hidden" value="OHZqni0fp1d97C2s5iPWk7uD5eZFh5kk-tWNzNLih18" name="form_token">
              <input type="hidden" value="search_block_form" name="form_id">
            </div>
          </div></form>  </div>
    </div>
    <div class="block block-system contextual-links-region block-menu" id="block-system-navigation">
      <h2>Navigation</h2>
      <div class="contextual-links-wrapper contextual-links-processed"><a href="#" class="contextual-links-trigger">Configure</a><ul class="contextual-links"><li class="menu-list first"><a href="/acquia_drupal/admin/structure/menu/manage/navigation/list?destination=node">List links</a></li>
          <li class="menu-edit"><a href="/acquia_drupal/admin/structure/menu/manage/navigation/edit?destination=node">Edit menu</a></li>
          <li class="block-configure last"><a href="/acquia_drupal/admin/structure/block/manage/system/navigation/configure?destination=node">Configure block</a></li>
        </ul>
      </div>
      <div class="content">
        <ul class="menu clearfix"><li class="first collapsed"><a href="/acquia_drupal/node/add">Add content</a></li>
          <li class="last leaf"><a href="/acquia_drupal/civicrm/dashboard">CiviCRM</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>



